version: '2'

volumes:
  data:

services:

  mysql:
    image: hypriot/rpi-mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
    ports:
      - "3306"
    volumes:
      - data:/var/lib/mysql
      
  web:
    build: .
    command: bundle exec rails server -p 3000
    ports:
      - "3000:3000"
    links:
      - mysql